/******Text-containing object definitions******/
/******IIFE 3 *********************************/

(function(){

var TechContainer = {
'En Ro' : [{
	original:'<h3>4. MAINTENANCE</h3> This section is a guide to properly maintain the equipment. Inspection and maintenance should be conducted at service intervals as stated below.<h4>4.1. CHECK LIST & REPLACEMENT INTERVAL</h4> Vibro ripper should be thoroughly inspected and serviced on a daily routine.<ul><li>(1) Before Starting-up<ul><li>Inspect all bots, nuts and screws. If necessary tighten them. (ex. Bolts for cushion elastomers & Motor, connections of hydraulic hoses)</li><li>Check the oil level in the gear box and if required, fill to the proper level.</li><li>Check hydraulic circuit for leaks (hoses, motor, pump)</li><li>Visually inspect all cushion elastomers for cracks and loose bolts</li><li>Check the condition of the tooth.</li><li>Check lubricating grease and refill if necessary.</li><li>Check that gear box and air breather for oil leakage.</li><li>Check the pressure of air spring, distortion or crack.</li><li>Check the noise of machine. If you hear strange noise, check all the bolts, motor, cushion elastomer. Rattling noises may indicate gear box failures or parts damage.</li></ul></li><li>(2) Every 50 ~ 100 hours or Monthly<ul><li>Change gear box oil after the first 50 hours of operation.</li><li>Check the grease and fill it if required.</li></ul></li><li>(3) Every 200 hours or Monthly<ul><li>Check the functioning of the motor and pump.</li></ul></li><li>(4) Every 400 hours or Two Monthly<ul><li>Change gear box oil after the every 400 hours of operation.</li></ul></li></ul>',
	translation: '<h3>4. MENTENANȚA</h3> Această secțiune este un ghid pentru mentenanța adecvată a echipamentului. Inspecțiile și operațiunile de mentenanță trebuie făcute la intervalele de service precizate mai jos.<h4>4.1. LISTĂ DE VERIFICARE ȘI INTERVALE DE ÎNLOCUIRE</h4> Plugul cu vibrații trebuie inspectat cu atenție și supus unor operațiuni de service conform unei rutine zilnice.<ul><li>(1) Înainte de pornire<ul><li>Inspectați toate bolțurile, piulițele și șuruburile. Dacă este cazul, strângeți-le (spre exemplu, bolțurile aferente elastomerilor-tampon și motorului sau conexiunile furtunurilor hidraulice).</li><li>Verificați nivelul de ulei din cutia de viteze și, dacă este cazul, umpleți cutia până la nivelul cerut.</li><li>Verificați ca circuitul hidraulic să nu aibă scurgeri (furtunurile, motorul, pompa).</li><li>Inspectați vizual toți elastomerii-tampon ca să vă asigurați că nu prezintă crăpături sau bolțuri desprinse.</li><li>Verificați starea ghearei.</li><li>Verificați nivelul lubrifiantului și completați-l dacă este nevoie.</li><li>Verificați cutia de viteze și orificiul pentru aer, ca să vă asigurați că nu există scurgeri de ulei.</li><li>Verificați presiunea resortului pneumatic și asigurați-vă că resortul nu prezintă distorsiuni sau crăpături.</li><li>Verificați zgomotul utilajului. Dacă auziți zgomote ciudate, verificați toate bolțurile, motorul și elastomerii-tampon. Zgomotele huruite pot indica defecțiuni ale cutiei de viteze sau avarii ale pieselor.</li></ul></li><li>(2) La fiecare 50 ̴ 100 ore de funcționare sau lunar<ul><li>Schimbați uleiul din cutia de viteze după primele 50 de ore de operare.</li><li>Verificați nivelul lubrifiantului și completați-l dacă este nevoie.</li></ul></li><li>(3) La fiecare 200 de ore de funcționare sau lunar<ul><li>Verificați funcționarea motorului și a pompei</li></ul></li><li>(4) La fiecare 400 de ore de funcționare sau la două luni<ul><li>Schimbați uleiul din cutia de viteze după fiecare 400 de ore de operare.</li></ul></li></ul>'
		}, {}, {}, {}
	],

'Ro En' : [{original:'<p>Caietele de Sarcini nu sunt specifice lucrarilor executate in santier. Pentru exemplificare se pune in atentie:</p><h4>Catetul de Sarcini pentru executia si controlul executiei structurilor din zidarie FAZA DDE (data: 2012.05.21)</h4><ul><li>in primul rand zidaria executata in cadrul santierului nu are rol structura, ci caramida plina presata are rol de suport pentru pictura iar caramida cu goluri, rol de termoizolatie;</li><li>in al doilea rand, prezentul caiet de sarcini, referitor la capitolul 2. de MATERIALE, nu prezinta nici un fel de cerinta tehnica specifica alegerii materialelor ce urmeaza a fi puse in opera (singura referire este: <i>&quot;La realizarea peretilor de tip ZIA (zidarie cu inima armata) se vor folosi numai caramizi pline din clasa I si mortar de ciment M100.&quot;</i>). Acest aspect aduce un conflict direct intre Executant si Beneficiar desfasurat pe parcursul anilor, conflict referitor la tipul de caramida ce urmeaza/este pus in opera la care au participat intens si colegii dumneavoastra din departamentul calitate.</li></ul><h4>Caietul de Sarcini pentru executia si controlul executiei structurilor metalice FAZA DDE (data: 2012.05.25)</h4><ul><li>prezinta cerinte specifice lucrarilor de confectie metalica in conditiile in care nu se executa acest tip de lucrare.</li><li>Proiectul Tehnic nr. 06/2010 prezinta lucrari de confectie metalica inglobate in beton armat (BAR) – Beton cu Armatura Rigida, tip de lucrare ce are in vedere alte normative, standarde si instructiuni fata de cele prezentate de catre Proiectant in continutul acestuia.</li><li>acest caiet de sarcini nu este corelat cu lucrarile de armare.</li><li>cele doua activitati (armatura rigida si armatura flexibila), <b> din cauza necorelării tolerantelor celor doua tipuri de lucrări in faza de proiectare, intra in conflict in cadrul procesului de execute.</b></li></ul><p>Nici un Caiet de Sarcini nu prezinta ordinea si tehnologia de executie avuta in vedere de catre Proiectant pentru un proiect special.</p>', 
translation:'<p>The Tender Books are not specific to the works executed on site. We are providing the following cases as an example:</p><h4> The Tender Book for executing and checking the execution of the masonry structures - DDE STAGE (dated: 2012.05.21)</h4><ul><li>First of all, the masonry works executed within the construction site do not play a structure role. Instead, the full pressed bricks play a supporting role for the paintings, while the hollow bricks are there for heat insulation purposes.</li><li>Secondly, the Tender Book mentioned here comprises no technical requirements in its Chapter 2, related to MATERIALS, e.g., there are no technical requirements related to the materials to be used in the works (the only such reference is related to <i>&quot;Executing the ZIA type walls (reinforced core walls) using only full, first class bricks and M100 cement mortar&quot;</i>). This issue has generated a direct conflict between the Executant and the Beneficiary, related to the type of bricks used/to be used in the works – a conflict that has been unfolding over the years and has largely involved your co-workers from the Quality Department as well.</li></ul><h4>The Tender Book for executing and checking the execution of the metallic structures – DDE STAGE (dated: 2012.05.25)</h4><ul><li>It comprises specific requirements applicable to metallic fixture works, despite the fact that no such works are executed on the site. Technical Project no. 06/2010 comprises metallic fixture works embedded in reinforced concrete (BAR) – Rigid Reinforcement Concrete – a type of work falling under totally different norms, standards and instructions, compared to the ones specified by the Designer in its Tender Book.</li><li>This Tender Book is not correlated with the reinforcement works.</li><li>The two activities (the rigid and the flexible reinforcement works) <b>entered in conflict with each other during the execution process, due to the fact that their tolerances had not been correlated during the design stage.</b></li></ul><p>None of the Tender Books specified the execution sequence or the execution technology taken into account by the Designer for this special project.</p>'}]
};

var LawContainer = {
	'En Ro' : [{original:'<p>There is one fundamental condition which needs to be satisfied before a person can take advantage of the Directives: being a lawyer. This condition is common to both the Services Directive and the Establishment Directive (the Lawyers&apos; Directives), as is the definition of the term &quot;lawyer&quot;, which follows in the next section.</p><h4>Who is a lawyer?</h4><p>Only those persons recognised by the Directives as being lawyers can benefit from the EU&apos;s free movement provisions for lawyers. The Establishment Directive defines a lawyer by listing two cumulative conditions:</p><ol><li> the person must be an EU national; and</li><li> the person must hold one of the professional titles listed within the Directive.</li></ol><p>In both Directives, the term &lsquo;lawyer&rsquo; is not defined by area or length of years of practice, nor by educational qualifications or years of study, but only by whether the person concerned holds one of the titles listed in the Establishment Directive. The titles refer to fully qualified lawyers. The holding of such a title, together with being a national of a Member State, entitles any fully qualified lawyer to take advantage of both of the Lawyers&apos; Directives. As a fully qualified lawyer holding a title listed in the Establishment Directive and the Services Directive the lawyers&apos; regime differs from most, or indeed probably from all other liberal professions.<p>In other liberal professions, the ability to cross borders is derived from a mutually recognised educational route to qualification, whereas in the legal profession it arises solely from the acquisition of a title, through whichever route that is nationally recognised. The routes to qualification as a lawyer in the Member States differ quite widely, with different emphasis placed (for instance) on practical or academic training. However, the Lawyers&apos; Directives override these differences, as they are based on the mutual recognition that each Member State has an adequate route to qualification with equivalent consumer protection.</p>', 
	translation: '<p>Există o condiție fundamentală care trebuie să fie satisfăcută înainte ca o persoană să poată profita de Directivele mai sus amintite: acea persoană trebuie să fie avocat. Această condiție este comună, aplicându-se atât în cazul Directivei Serviciilor cât și în cazul Directivei Stabilirii (Directivele privind avocații), și la fel este și definiția termenul de &quot;avocat&quot;, prezentată în secțiunea următoare.<h4>Cine este avocat?</h4><p>Doar acele persoane care sunt recunoscute de către Directive ca fiind avocați pot beneficia de prevederile privind libera circulație a avocaților în interiorul UE. Directiva Stabilirii definește un avocat, enumerând două condiții ce trebuie îndeplinite cumulativ:</p><ol><li>Persoana respectivă trebuie să fie cetățean al unui stat UE și</li><li>Persoana respectivă trebuie să dețină unul dintre titlurile profesionale enumerate în Directivă.</li></ol><p>În nici una dintre Directive, termenul de &quot;avocat&quot; nu este definit prin prisma domeniului sau a numărului de ani de practică și nici prin cea a calificărilor profesionale sau a numărului de ani de studii, ci doar prin prisma deținerii, de către persoana în cauză, a unuia dintre titlurile profesionale enumerate în Directiva Stabilirii. Aceste titluri se referă la avocații pe deplin calificați. Orice avocat pe deplin calificat care deține un astfel de titlu și este cetățean al unui stat membru UE are dreptul să profite de ambele Directive privind avocații. Regimul avocaților pe deplin calificați, care dețin un titlu profesional menționat în Directiva Stabilirii și în Directiva Serviciilor, este diferit de regimurile majorității, dacă nu chiar de regimurile tuturor celorlalte profesii liberale.</p><p>În celelalte profesii liberale, posibilitatea de a activa dincolo de granițe derivă dintr-un parcurs educațional de calificare recunoscut reciproc, în vreme ce, în cazul profesiei juridice, această posibilitate izvorăște exclusiv din obținerea unui titlu profesional, prin orice mijloace recunoscute la nivel național. Parcursurile de calificare pentru avocați diferă destul de mult de la un stat membru la altul, cu importanțe diferite acordate (spre exemplu) pregătirii practice sau celei academice. Totuși, Directivele privind avocații suprascriu aceste diferențe, fiind bazate pe recunoașterea reciprocă a faptului că există, în fiecare stat membru, un parcurs adecvat de calificare pentru avocați și un nivel echivalent de protecție a consumatorilor.</p>'}],

	'Ro En' :[{original:'<p><em>Declaram ca in urma procedurii de mediere realizate de XXX in calitate de mediator, autorizat prin hotararea Consiliului de Mediere nrXXX eliberata la data de 04.04.2012, am solicitat incheierea prezentului acord liber exprimat si neafectat de nici un viciu de consimtamant, fiind intru-totul de acord cu cele convenite, dupa cum urmeaza:</em></p><ol><li><h4>EXERCITAREA AUTORITATII PARINTESTI</h4><ol><li>Exercitarea autoritatii parintesti asupra minorului XXX se va face de mama, adica de XXX, conform intelegerii partilor.</li></ol></li><li><h4>STABILIREA LOCUINTEI COPILULUI</h4><ol><li>Locuinta minorului XXX, este stabilita la parintele cu care va locui in mod statornic, adica XXX.</li><li>Locuinta minorului XXX va fi in XXXX.</li></ol></li><li><h4>PASTRAREA LEGATURILOR PERSONALE CU COPILUL</h4><ol><li>Pastrarea legaturilor personale dintre parintele separat si copil se va face ori de cate ori este necesar si/sau la dorinta expresa a copilului.</li><li>Mama va decide asupra modului de crestere si educare al minorului in mod exclusiv.</li><li>Deoarece exercitarea autoritatii parintesti se va realiza de mama, acordul tatalui pentru iesirile din tara, vacante in strainatate, spitalizari, este dat prin prezentul acord de mediere si va fi supus consfintirii de catre instanta de judecata.</li><li>Pe perioada sarbatorilor legale musulmane parintele separat va putea avea legaturi personale cu copilul in jumatate din timpul cat acestea au loc, dupa implinirea varstei de 10 ani a minorului. Aceasta intelegere poate fi modificata oricand prin intelegerea parintilor sau la cererea expresa a copilului;</li><li>Mama va putea decide cu privire la programul minorului, inclusiv excursii, vizite in afara domiciliului; fara a mai fi necesar acordul tatalui;</li><li>Mama va putea decide in grija cui lasa minorul atunci cand este plecata din oras, in interes de serviciu, etc.</li><li>Pentru obtinerea cartii de identitate, pasaportului sau altor acte de stare civila, a unor legitimatii, permis de conducere, sau alte documente care necesita acordul parintilor, parintii sunt de acord ca hotararea judecatoreasca ce se va da in baza prezentului acord sa tina loc de consimtamant al parintelui separat, documentele urmand a fi solicitate, depuse si ridicate de catre mama in numele copilului;</li></ol></li></ol>', 
	translation: '<p><em>We hereby state that, following the mediation procedure conducted by mediator XXX, certified for practice under Decision no. XXX, issued by the Mediation Council on 04.04.2012, we have requested the conclusion of the hereby Mediation Agreement, which is freely consented by us and does not suffer from any consent impairments, and we fully adhere to the things agreed upon, as follows: </em></p><ol><li><h4>EXERTING PARENTAL AUTHORITY</h4><ol><li>Parental authority shall be exerted over the minor child XXX, by his mother, XXX, according to the agreement reached between the Parties.</li></ol></li><li><h4>DETERMINING THE CHILD&apos;S DOMICILE</h4><ol><li> The domicile of the minor child XXX, is hereby set to be at the parent the child shall live with, on a steady basis, e.g., XXX.</li><li> The domicile of the minor child XXX shall be in XXX.</li></ol></li><li><h4>KEEPING PERSONAL CONNECTIONS WITH THE CHILD</h4><ol><li>Personal connections shall be kept between the alienated parent and the child, whenever necessary and/or upon the child’s express wish.</li><li> The mother shall be the one to decide exclusively on the way the minor child is to be raised and educated.</li><li> Since the mother shall be the one exerting parental authority over the child, the father’s consent for trips and vacations abroad, for hospitalisations, etc. is hereby granted through this mediation agreement and it shall be submitted to the Court for approval.</li><li> During legal Muslim holidays, the alienated parent shall be allowed to have personal relations with the child, over half of such holidays’ period, after the minor turns 10. This agreement can be modified at any time, by mutual consent of both parties or upon express request from the child.</li><li> The mother shall be entitled to decide on the minor child’s schedule, including his trips, his visits outside his domicile, without needing the father’s consent.</li><li> The mother shall be entitled to decide who she leaves in charge of the child’s care when she is out of town for business purposes, etc.</li><li> For the purpose of issuing the child’s identity card, his passport or other vital records documents, as well as badges, his driving license or other documents that require the consent of both parents, the parents hereby agree to consider the Court Ruling to be issued based on this Agreement, as a replacement for the alienated parent’s consent, and thus, all the above mentioned documents shall be requested, submitted and picked up by the mother, on behalf of the child.</li></ol></li></ol>'}]
};


var EconContainer = {
	'En Ro' : [{original:'<h4>Principal risks and uncertainties</h4><p>The company continuously carries out an assessment of the risks which have the potential to have a significant negative impact on its financial performance and future business prospects, The company has a low appetite for risk.</p><dl><dt>Price risk:</dt><dd>Price risk is defined as the risk of a material loss arising from exposures to excessive price fluctuations in positions held by the company. Because all client positions are hedged with XXX, this risk is materially mitigated.</dd><dt>Credit risk:</dt><dd>Credit risk arises where a borrower or counterparty fail to meet their financial obligations. The main source of credit risk for the company is on deposits held at third parties. No credit is extended to clients. To mitigate this risk, all customer funds are held in a UK regulated clearing bank, and the company&apos;s own funds are held across a number of European banks.</dd><dt>Cash flow risk:</dt><dd>Cash flow risks are that the company does not have sufficient financial resources to meet its obligations as they fall due. Under the company&apos;s business model, the most likely reason for this to happen would XXX not being able pay the company any amounts due, leaving the company unable to settle its obligations with its clients, or vice versa, The company has controls in place to ensure that clients do not owe more than their deposit, and is given reports by XXX which demonstrates that they are operating within their own risk parameters.</dd></dl>', 
	translation: '<h4>Principalele riscuri și incertitudini</h4><p>Compania evaluează în mod constant riscurile care ar putea avea un impact semnificativ asupra performanțelor sale financiare și asupra perspectivelor sale viitoare de afaceri. Compania are un apetit scăzut pentru riscuri.</p><dl><dt>Riscul de preț:</dt><dd>Riscul de preț este definit ca fiind riscul unei pierderi materiale în urma expunerii la fluctuații excesive ale prețurilor în pozițiile deținute de companie. Cum toate pozițiile clienților sunt acoperite împreună cu XXX, acest risc este substanțial redus.</dd><dt>Riscul de credit:</dt><dd>Riscul de credit apare atunci când un împrumutat sau o contra-parte nu reușește (nu reușesc) să își îndeplinească obligațiile financiare. Principala sursă de riscuri de credit pentru companie este reprezentată de depozitele deținute la terți. Nu se oferă nici un credit clienților. Pentru a reduce acest risc, fondurile clienților sunt păstrate într-o bancă reglementată de clearing din Regatul Unit, iar fondurile proprii ale Companiei sunt păstrate în mai multe bănci europene.</dd><dt>Riscul fluxului de numerar:</dt><dd>Riscurile fluxului de numerar sunt riscurile ca această companie să nu aibă suficiente resurse pentru a-și îndeplini obligațiile pe măsură ce acestea devin scadente. Potrivit modelului de activitate al Companiei, cel mai probabil motiv pentru un astfel de scenariu ar fi ca XXX să nu poată să achite Companiei nici o sumă datorată, punând astfel Compania în imposibilitatea de a-și îndeplini propriile sale obligații față de clienți sau vice-versa. Compania are fixate mijloace de control pentru a se asigura că clienții nu datorează sume mai mari decât cele aflate în depozitele lor și primește rapoarte de la XXX care demonstrează că această firmă operează în limitele propriilor săi parametri de risc.</dd></dl>'}],
	'Ro En' :[{original:'<h4>Scop:</h4><p>XXX este un start-up inovator care isi doreste sa revolutioneze modul in care ne cautam medicul de care avem nevoie si ne facem programarile necesare.</p><h4>Obiective:</h4><ul><li>Recunoasterea nationala a XXX ca <strong>&quot;Prima Aplicație din România de programări online la doctor&quot;</strong>;</li><li>Lansarea oficiala a aplicatiei pana la sfarsitul anului 2016 cu clinici medicale doar din Bucuresti cu un numar total de aproximativ 1,000 doctori;</li><li>Pana la sfarsitul anului 2017 listarea a 5,000 doctori in Bucuresti si 10,000 la nivel national cu un pret mediu de 10 euro/luna/doctor (abonament) sau 1 euro/programare;</li><li>Break-even pana in iulie 2016;</li><li>Lansarea aplicatiei si in alte tari incepand cu 2018 acolo unde XXX a cumparat deja domenii web;</li><li>Demararea proceduriliror pentru obtinerea protectiei internationale in tarile unde se doreste lansarea aplicatiei.</ul><h4>Strategii:</h4><ul><li>Securizarea pozitiei pe piata la nivel national si a unei cote de piata majoritare, inainte de aparitia altor furnizori competitivi, prin:<ol style="list-style-type:lower-alpha"><li>semnarea a cat mai multe contracte cu clinici medicale pana la finalul anului 2017, atat in Bucuresti si marele orase universitare din tara (Cluj, Iasi, Timisoara), cat si cu clinicile din restul localitatilor tarii.</li><li>oferta pormotionala de 1 luna utilizare gratuita pentru clinici medicale.</li></ol><li>Incheierea de parteneriate/contracte de servicii cu furnizorii solutiilor IT ale clinicilor pentru sincronizarea softului Docbook cu softul clinicilor, la un cost mediu de 2 euro/medic/luna.</li><li>Vanzarea unui pachet de actiuni dupa primele 6 luni de la lansare catre un investitor strategic care sa asigure resursele financiare necesare ca XXX sa se lansesze si in alte tari.</li></ul>', 
	translation: '<h4>Purpose:</h4><p>XXX is an innovating start-up that wants to revolutionise the way we look for the doctor we need and the way we make the necessary appointments.</p><h4>Objectives:</h4><ul><li>XXX&apos;s nationwide recognition as <strong>&quot;The first online doctor appointment platform in Romania&quot;</strong>.</li><li>The official launch of the application by the end of 2016, comprising only clinics located in Bucharest, with a total number of approximately 1,000 doctors.</li><li>By the end of 2017, we want to have 5,000 doctors listed in our application, in Bucharest alone and 10,000 at national level, with an average price of 10 euro/month/doctor (for subscriptions) or 1 euro/appointment.</li><li>Break-even by July 2016.</li><li>As of 2018, we intend to launch the application abroad, in countries where XXX has already bought the relevant web domains.</li><li>Initiating the necessary procedures to obtain international protection in those countries where the application is to be launched.</li></ul><h4>Strategies:</h4><ul><li>Consolidating our position on the market, at national level and securing a majority market share before other competitor suppliers come into play, by:<ol style="list-style-type:lower-alpha"><li>Signing as many contracts as we can, with as many medical clinics, by the end of 2017, both in Bucharest and in the major university centres in Romania (Cluj, Iasi, Timisoara) and in other towns and settlements in the country.</li><li>Promotional offer to use the platform free of charge for a month, for medical clinics.</li></ol><li>Concluding partnerships/service provision contracts with the clinics&apos; IT solution suppliers, in view of synchronising the XXX software with the software used by these clinics, at an average cost of 2 euro/doctor/month.</li><li>Selling a first share package, 6 months after the company is launched, to a strategic investor who would provide the necessary financial resources that would allow XXX to launch abroad as well.</li></ul>'}]
};

var LiterContainer = {
	'En Ro' : [{original:'<p><i>(There are three people in the show: <b>Steve</b>, <b>Yelena</b>, and <b>Allen</b>. The stage is bare, except for a piano, which is played by <b>Steve</b> and <b>Yelena</b>, a piano bench, a chair, and a coat rack full of costumes, hats, and hand props. Upstage center and overhead is a screen on which supertitles (the italicized translations and song/scene titles in the text) are projected. We begin in black with <b>Yelena</b> singing and <b>Steve</b> on piano.) </i></p><p><b>Yelena</b>: Of all the boys I&apos;ve known and I&apos;ve known some<br>Until I first met you I was lonesome<br>And when you came in sight, dear, my heart grew light<br>And this old world seemed new to me<br>You&apos;re really swell, I have to admit you<br>Deserve expressions that really fit you<br>And so I&apos;ve racked my brain hoping to explain<br>All the things that you do to me<br></p><p>All: Yiddish.</p><p><b>Yelena</b>: That song is from Yiddish theater.</p><p><b>Steve</b>: Yiddish? What&apos;s Yiddish?</p><p><b>Yelena</b>: Yiddish?</p><p><b>Allen</b>: Yiddish? Yiddish is the secret language of genius geeks. Not that many people speak it today, but when people who do get together they immediately switch to Yiddish and have these bizarre private conversations, like spies.</p><p><b>Yelena</b>: It&apos;s an amazing language for expressing emotion, and it&apos;s an incrediblelanguage for humor.</p><p><b>Steve</b>: Joseph Papp, one of the greatest theatre producers who ever lived, said Yiddish is the perfect language for theatre. Because Yiddish sounds theatrical.</p><p><b>Yelena</b>: You see, in Yiddish you can&apos;t just say something, you have to make it interesting. You can&apos;t say <b>Steve</b>: To be or not to be... that is the question.</p><p><b>Yelena</b>: You have to say <mark>Zayn oder nit zayn... du ligt der hint bagrubn.</mark></p><p><b>Steve</b>: To be or not to be... that&apos;s where the dog is buried.</p><p><b>Allen</b>: For example. In the following scene three friends are out fishing. First, in English.</p><p>(They sit as on a boat and use dowels for fishing poles.)</p><p><b>Steve</b>: Anything doing over there?</p><p><b>Allen</b>: Not a nibble.</p><p><b>Yelena</b>: Nothing.</p><p><b>Steve</b>: This is just terrible.</p><p><b>Yelena</b>: Why are we bothering?</p><p><b>Allen</b>: It&apos;s a waste of time.</p><p><b>Yelena</b>: It&apos;s totally pointless.</p><p><b>Allen</b>: There used to be so many fish here, really.</p><p><b>Steve</b>: Let&apos;s get out of here. Let&apos;s get some sandwiches.</p><p><b>Yelena</b>: That&apos;s a very good idea.</p><p><b>Steve</b>: Okay.</p><p><b>Allen</b>: <i>(they bow, very dignified) </i>...Boring, right? Okay, now here&apos;s the exact same scene in Yiddish. If you don&apos;t know the language yet, read the supertitles.</p>', 
translation: '<p><i>(Spectacolul are trei personaje: <b>Steve</b>, <b>Yelena</b> și <b>Allen</b>. Scena este goală, cu excepția unui pian, la care cântă <b>Steve</b> și <b>Yelena</b>, a unei băncuțe pentru pian, a unui scaun și a unui cuier pentru haine, plin de costume, de pălării și de proteze de recuzită pentru mâni. În centrul scenei, în partea de sus, se află un ecran pe care sunt proiectate subtitrările (traducerile scrise cu litere italice și titlurile cântecelor/ale scenelor din text). Începem pe întuneric, cu <b>Yelena</b> cântând vocal și <b>Steve</b> la pian.)</i></p><p><b>Yelena</b>: Cu toți băieții întâlniți pe-aici de mine<br>Am fost singură până să te cunosc pe tine<br>Și când prima oară ai apărut în fața mea, mi-a stat în loc inima<br>Iar această lume prăfuită mi-a părut din nou în lumină poleită<br>Ești extraordinar și trebuie să găsesc<br>Cuvinte și expresii ce ți se potrivesc<br>Așa că mi-am stors creierii încercând să explic<br>Toate lucrurile pe care cu tine le simt<br></p><p>Toți: Text în idiș.</p><p><b>Yelena</b>: Acest cântec este din teatrul idiș.</p><p><b>Steve</b>: Idiș? Ce-i aia idiș?</p><p><b>Yelena</b>: Idiș?</p><p><b>Allen</b>: Idiș? Idiș este limba secretă a tocilarilor geniali. Astăzi nu o mai vorbește multă lume dar, atunci când se adună laolaltă mai mulți oameni care o vorbesc, trec imediat la idiș și poartă niște conversații private bizare, ca spionii. </p><p><b>Yelena</b>: Este o limbă excelentă pentru exprimarea emoțiilor și incredibilă când vine vorba de umor.</p><p><b>Steve</b>: Joseph Papp, unul dintre cei mai mari producători de teatru din toate timpurile a spus că idiș este limba perfectă pentru teatru. Pentru că sună teatral. </p><p><b>Yelena</b>: Vezi tu, în idiș nu poți să spui pur și simplu ceva, trebuie să o spui într-un mod interesant. Nu poți spune...</p><p><b>Steve</b>: A fi sau a nu fi... aceasta este întrebarea.</p><p><b>Yelena</b>: Trebuie să spui <i><sup>Zayn oder nit zayn... du ligt der hint bagrubn.</sup></i></p><p><b>Steve</b>: A fi sau a nu fi.....acolo e-ngropat câinele.</p><p><b>Allen</b>: Spre exemplu, în scena următoare, trei prieteni se duc la pescuit. Mai întâi, în engleză:</p><p>(Se așează ca și cum s-ar afla într-o barcă și folosesc dibluri pe post de undițe).</p><p><b>Steve</b>: Mușcă ceva acolo?</p><p><b>Allen</b>: Nici măcar o îmbucătură mică.</p><p><b>Yelena</b>: Nimic.</p><p><b>Steve</b>: E îngrozitor.</p><p><b>Yelena</b>: De ce ne mai obosim?</p><p><b>Allen</b>: E o pierdere de timp.</p><p><b>Yelena</b>: N-are nici un rost.</p><p><b>Allen</b>: Cândva, erau foarte mulți pești aici, pe bune.</p><p><b>Steve</b>: Hai să plecăm de aici. Să luăm niște sandvișuri.</p><p><b>Yelena</b>: Bună idee.</p><p><b>Steve</b>: Bine.</p><p><b>Allen</b>:<i>(fac o plecăciune, cu un aer de demnitate)...</i> Plictisitor, nu? Bine, acum, iată exact aceeași scenă, în idiș. Dacă nu vorbiți încă limba, citiți subtitrarea. </p>'}],
	'Ro En' :[{original:'<h4>&bdquo;Sunt irațional și mă mândresc cu asta...!&rdquo;</h4><p>Iată un fapt de care nu toți oamenii sunt conștienți:</p><p><em><b>Problema legată de felul în care acționăm în prezent (fiindcă așa am fost învățați) este aceea că, de regulă, ne folosim în mod intensiv și extensiv de rațiune pentru a genera realitatea viitoare. Luăm, cel mai adesea, decizii raționale. <u>Dar orice rezultat extraordinar în viitor, orice schimbare adevărată, minunată, vine la început dintr-o decizie irațională, bazată pe un vis ce poate părea incredibil!</u> Ceea ce contrazice din start, calea rațională către succes.</b></em></p><p> Orice om care a realizat ceva măreț avea inițial doar un Vis, adică o <i>dorință irațională</i> atunci când a pornit la drum. Prin contrast, deciziile raționale, deși excelente pe termen scurt - pentru că ne apără de tot felul de lucruri (reacția în fața unui pericol imediat, spre exemplu) - ne condamnă la eșec pe termen lung, dacă le folosim ca mecanism fundamental de ghidare. </p><p>Majoritatea oamenilor folosesc mecanisme logice, raționale, pragmatice drept mecanisme fundamentale de luare a deciziilor. Și am observat <u>că tocmai aceia care folosesc căile raționale în mod intensiv sau excesiv eșuează cel mai des.</u></p><p>Pentru că – așa cum am stabilit anterior - emoțiile sunt cele care ne ghidează drumul și nu rațiunea. Rațiunea este extraordinară ca unealtă, ea face parte din proces și este o parte extrem de importantă a conștiinței; dar puterea ei este limitată. Avem, în fapt, doar <u>senzația</u> că luăm decizii raționale. </p><p><em>În realitate, decidem in funcție de felul în care o variantă sau alta este percepută ca fiind fie mai puțin periculoasă, fie mai atrăgătoare. Prin urmare, cel mai adesea, ori frica, ori speranța sunt cele care guvernează de fapt răspunsul rațional. Și ambele sunt emoții!</em></p>', 
	translation: '<h4>&bdquo;I&apos;m Irrational And Proud Of It...!&rdquo;</h4><p>Here is something not all people are aware of:</p><p><em><b>The problem with the way we act today (because that&apos;s how we have been taught to act) is that we frequently use reason, in an incisive and extensive way, in order to generate our future reality. Most of the times, we make rational decisions. <u>While any extraordinary result in the future, any true, wonderful change, has to start with an irrational decision, based on a dream that may seem incredible! </u>And this excludes, from the very beginning, any rational path towards success. </b></em></p><p>Anybody who has ever achieved anything important, started, initially, with just a Dream, an <i>irrational desire</i>. By comparison, rational decisions, although excellent on a short term – because they protect us from many unpleasant things (such as our reaction to an immediate danger, for instance) – sentence us to long term failure, if we use them as our fundamental guiding system. </p><p><em>Most people use rational, logical, pragmatic mechanisms, as their main decision making tools. And I&apos;ve noticed that <u>those using rational paths intensively or excessively, are the ones who fail the most.</u></em></p><p>Because - as we have said earlier- emotions, and not reason, are the ones guiding us on our path. Reason is an extraordinary tool, it is part of the process and a very important part of our conscience; But it has limited powers. In fact, we are only under <u>the impression</u> that we are making rational decisions.</p><p><em>In reality, we decide based on the way we perceive one option or the other, to be either less dangerous or more attractive. Therefore, most of the times, the one governing our rational responses is either fear or hope. And these are both emotions!</em></p>'}]
};

var LoremIpsum = [{
	original:"<p>Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec bibendum odio eget erat suscipit pharetra. Suspendisse turpis urna, mattis vel posuere vel, tincidunt eu dolor. Aenean vel odio vitae urna semper tristique. Phasellus fermentum mollis diam, sit amet scelerisque magna tempus ut. Nullam rhoncus tellus sed lorem congue egestas. Aenean ornare ornare neque, sit amet venenatis sem convallis vel. Cras efficitur eu dolor nec consectetur. Integer hendrerit ante scelerisque orci posuere, non sollicitudin dui laoreet. Donec sit amet odio orci.</p><p>Suspendisse laoreet eros nec elit mattis, nec volutpat magna interdum. Proin sodales magna a ante scelerisque, sed faucibus lorem tempus. Maecenas nunc ligula, sagittis sagittis massa ut, luctus dignissim urna. Duis a lorem imperdiet, convallis leo sit amet, semper sapien.</p><p>Mauris id commodo tellus. Phasellus sit amet dictum felis, in sollicitudin augue. Sed tempus nisi in dolor tincidunt commodo in ac tortor. Nunc vel metus tempor, consequat tortor vitae, scelerisque metus. Morbi nec elit a orci lacinia dapibus. Maecenas quis dui varius, faucibus quam ac, dapibus nisl. Phasellus ornare orci at mi porta, nec feugiat nibh finibus. Sed ornare sem nec leo porttitor lobortis.</p>",
	translation:"<p>Ut dictum feugiat lectus in auctor. Fusce vestibulum scelerisque metus quis elementum. Praesent viverra mi sed ex eleifend pellentesque ac fringilla velit. Donec eget ultricies leo. Cras nibh nibh, tempor in libero quis, consequat tempor eros. Pellentesque ultricies, metus ut condimentum vestibulum, nulla nisi consectetur ipsum, sed interdum mauris nisi posuere velit. Phasellus felis neque, lacinia non semper nec, sagittis non arcu. Mauris id commodo tellus. Phasellus sit amet dictum felis, in sollicitudin augue.</p><p>Cras viverra arcu justo, a porta nibh bibendum quis. Vivamus dui erat, luctus semper facilisis id, consequat eget nibh. Donec egestas orci sed justo finibus laoreet. Fusce pellentesque vitae lectus eu imperdiet. Proin a dictum purus, in ullamcorper felis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc eget consectetur lectus. Nunc vulputate, ligula eu tincidunt iaculis, neque quam rhoncus sapien, fermentum pellentesque sapien eros in ipsum.</p><p>In id purus vel velit convallis tincidunt. Nulla molestie, sapien eget sagittis malesuada, mi nulla volutpat est, non sollicitudin est urna eget ligula.</p>"

}, {original:'<h4>Hotel și servicii</h4><p>Hotelul XXX este recent redeschis publicului, după un proces de renovare care a durat mai bine de un an. Hotelul și-a reluat activitatea în aprilie 2016, având un aspect modern și un personal calificat. XXX este cel mai mare hotel de 3 stele din Suceava, fiind situat în centrul orașului, la 3 minute de mers pe jos de centrul vechi.</p><p>Hotelul oferă acces facil nu doar la principalele instituții din oraș: Casa de Cultură a Sindicatelor, Consiliul Județean Suceava, Palatul de Justiție, Administrația Județeană a Finanțelor Publice Suceava, Prefectura, ci și la obiectivele turistice locale: Muzeul de Științe ale Naturii, Muzeul de Istorie, Casa Memorială Simion Florea Marian, parcul central, în care se regăsește Biserica Catolică, Cetatea de Scaun și Muzeul Satului Bucovinean.</p><p>Pe lângă serviciile de cazare, clienții pot opta pentru servicii de alimentație publică în restaurant, bar de zi și cele doua terase ale hotelului, pentru servicii de închiriere săli de conferință, room service și catering.</p><p>Oferta hotelului conține o listă de servicii directe si complementare: parcare privată securizată, internet wireless de mare viteză oferit gratuit turiștilor, serviciu bagajist în ambele sensuri, seif pentru bunuri și valori, telefon cu acces național și internațional, apel de trezire, acces animale de companie iar la cerere se pot asigura transferul de la gară și aeroport, tururi de mănăstiri și alte obiective din oraș și din împrejurimi.</p>',
translation:'<h4>Hotel and services</h4><p>The XXX Hotel has been recently re-opened to the public after a refurbishment process that took over one year. The hotel resumed its activity in April 2016, with a new, modern look and highly qualified personnel. XXX is the largest three star hotel in Suceava, located in the middle of the town, with the old city centre only a three minute walk away. </p><p>The hotel provides easy access both to the main institutions in town: The Syndicates&apos; Palace of Culture, the Suceava County Council, the Palace of Justice, the County Tax Authority, the Prefect&apos;s Office (<i>Biroul Prefectului</i>), and to the main local tourist attractions: The Natural Science Museum, the History Museum, the &quot;Simion Florea Marian&quot; Memorial House, the central park, where you can find the Catholic Church, the Old Ruler&apos;s Seat Fortress (Cetatea de Scaun) and the Bucovina Village Museum. </p><p>Besides accommodation services, our clients can also choose our meal services in the hotel&apos;s restaurant, in its day bar and in its two terraces, as well as our conference halls, our room service and our catering services. </p><p>The hotel&apos;s offer comprises a list of direct and complementary services: private guarded parking, free high speed wireless internet for tourists, luggage transportation services both ways, a vault for valuable assets, national and international access phone, wake up call, pets allowed and, upon request, we can also make arrangements for your transportation form the railway station or from the airport, we can book tours to the Monasteries for you and we can arrange visits to other tourist attractions in town and in the nearby areas. </p>'}
];

var navSect = {
top:['Traduceri autorizate, realizate precis și prompt', 'Prompt and accurate certified translations'],

p1:['Dacă ai nevoie de serviciile unui traducător autorizat de limba engleză, atunci te afli în locul potrivit iar această pagină îți va furniza informațiile necesare. Numele meu este Irina și activez în branșa traducătorilor din anul 2014. Am lucrat într-o firmă de traduceri dar, la un moment dat, am decis că pot să realizez mai mult ca freelancer, așa că am început să lucrez pe cont propriu.', 'If you are in need of a certified English translator, you are in the right place. This page will provide you with all the information that you need. My name is Irina and I have been working as a translator since 2014. At the beginning of my career,  I worked for a Translation Services  Agency but, after a while, I realised that I could do more as a freelance translator so I started working on my own.'],

p2:['Mă poți găsi și pe pagina Ministerului Justiției, în lista de traducători autorizați, urmând acest <a href="http://old.just.ro/MinisterulJusti%C8%9Biei/Listapersoanelorautorizate/Interpretisitraducatoriautorizati/tabid/129/Default.aspx" target="_blank"> link.</a>', 'You can find me on the Justice Ministry&apos;s webpage, on the list of certified legal translators, <a href="http://old.just.ro/MinisterulJusti%C8%9Biei/Listapersoanelorautorizate/Interpretisitraducatoriautorizati/tabid/129/Default.aspx" target="_blank">here.</a>'],

p3:['Am activat un număr de ani în presa centrală, ca jurnalist de politică externă. Aici, am lucrat zilnic cu  fluxuri și canale de știri internaționale,  care sunt scrise și transmise exclusiv in limba engleză.  În plus, munca de jurnalist m-a pregătit, indirect, pentru cea de traducător, obligându-mă să îmi fac o a doua natură din respectarea deadline-urilor strânse. De mare ajutor mi-au fost și călătoriile profesionale peste hotare, în care am asistat, în calitate de jurnalist, la diverse evenimente politice.  Acestea  mi-au oferit oportunitatea să mă familiarizez cu engleza și franceza vorbite de nativi și de non-nativii din alte țări.', 'Before becoming a translator, I worked as a Foreign Affairs Journalist for years.   Here, I had to work with international news wires and channels written and aired exclusively in English, on a daily basis.  Besides, my experience as a Journalist has practically taught me to live on a deadline and to never submit an assignment late, no matter how tight the deadline was. This skill has proven to be very useful in my work as a translator.  My professional trips abroad, to cover various political events as a Journalist, have also been very useful to me, because they gave me the opportunity to get acquainted with various types of English and French spoken by both native and non-native speakers in other countries.'],

ellipsis1:['&hellip; (click pentru mai mult text)', '&hellip;  (click to see more)'],

ellipsis2:['(click pentru a ascunde din text)', '(click to collapse text)'],

p4:['Dar lucrul care a contribuit cel mai mult la îmbunătățirea nivelului meu de engleză a fost experiența de studii în străinătate.  Am urmat în ultimii ani două programe de master în limba engleză, unul  în Jurnalism (la Dublin City University, Irlanda) iar celălalt în Dezvoltare și Relații Internaționale (Universitatea Aalborg, Danemarca). În timpul primului program am avut ocazia să iau contact direct cu engleza vorbită în Australia, la Sydney, în cadrul unui semestru petrecut  la University of Technology, într-un schimb de experiență. Am, așadar, o experiență relativ bogată în explorarea universului limbii engleze pe mai multe meridiane, prin interacțiuni cu o mare varietate de vorbitori.', 'But the thing that helped me improve my English the most was my study abroad experience. During the past few years, I have completed two Master’s programmes in English, one in International Journalism (at Dublin City University in Ireland) and another one in Development and International Relations (at Aalborg University, Denmark). During my first Master’s programme, I had the chance to experience, first hand, the English spoken in Australia, during a semester spent as an exchange student, at University of Technology Sydney.  Thus, I can say that I have a rather wide experience of interacting with various  English speakers worldwide.'],

p5:['În ceea ce privește activitatea din prezent, am tradus și traduc în continuare pentru clienți dintr-o diversitate de industrii - construcții, petrol, bănci, servicii avocațiale. Poți vedea câteva exemple de materiale traduse în secțiunea specializată din meniul de mai jos. Prețurile practicate sunt <a href="#pricing">accesibile și sub media pieței</a>. Mai multe despre mine poți afla urmând link-ul către pagina personală.', 'As to my current activity, I have been translating various documents for clients working in a wide range of industries – constructions, oil, banks, legal services. You can see several samples of my work in the specialised section in the menu below. My rates are accessible and below the market average. You can find out more about me, by clicking the link leading to my personal page. '],

navig:['Navigare', 'Navigation'],

servPricing:['Servicii și prețuri', 'Services and rates'],

samples:['Mostre de traducere', 'Translation samples'],

about:['Despre', 'About']
}


var mainSect = {

samplesTitle:['Mostre de traducere', 'Translation samples'],

p6:['Click pe butoanele corespunzătoare pentru afișarea unei mostre de traducere dintr-un anumit domeniu. Mostrele din coloana &quot;Text Original&quot; păstrează forma primită de la client. Unele nume de persoane fizice și juridice au fost anonimizate pentru respectarea clauzelor de confidențialitate. La acționarea butoanelor, opțiunea implicită este limba româna ca limbă-țintă (adică se vor afișa traduceri En-Ro). Pentru traduceri Ro-En bifați căsuța înainte de click.', 'Click on the appropriate buttons to see a translation sample from a certain domain. The samples in the &quot;original text&quot; columns were listed in their original form received from the clients. Certain names of people and legal entities have been censored for confidentiality reasons. When clicking a button, the default option is Romanian as a target language (e.g., the translations shown will be En-Ro). For Ro-En translations, tick the corresponding box before clicking.  '],

techTr:['Traducere tehnică', 'Technical translation'],

lawTr:['Traducere juridică', 'Legal Translation'],

econTr:['Traducere economică', 'Economic Translation'],

literTr:['Traducere literară', 'Literature Translation'],

sourceTitle:['Text Original', 'Original Text'],

targetTitle:['Traducere', 'Translation'],

servTitle:['Servicii', 'Services and rates'],

p7:['Click pe butonul corespunzător pentru afișarea prețurilor.', 'Click on the appropriate button to see the rates'],

trDetails:['Traducere', 'Translations'],

intDetails:['Interpretariat', 'Interpreting Services'],

specDetails:['Specials', 'Specials'],

itPriceContent: [['<dl><dt>Traducere din limba engleză în limba română:</dt><dd>15 RON pagina<sup><small>*</small></sup></dd><dt>Traducere din limba română în limba engleză:</dt><dd>11 RON pagina<sup><small>*</small></sup></dd><dd><sup><small>*</small></sup>O pagină standard A4 este evaluată la 2000 de caractere, inclusiv spațiile. Prețul afișat este cel final, facturat pentru client.</dd></dl>', '<dl><dt>Interpretare consecutivă(notariate, Poliție, instanțe etc):</dt><dd>100 RON ora<sup><small>*</small></sup></dd><dt>Interpretare simultană (conferințe, radio, TV):</dt><dd>100 RON ora<sup><small>*</small></sup></dd><dd><sup><small>*</small></sup>Prima oră se tarifează la preț întreg, indiferent de durata serviciului. Următoarele ore sunt tarifate fracționat, la 30 de minute. Prețul afișat este cel final, facturat pentru client.</dd></dl>', '<dl><dt>Interpretări pe parcursul unei zile / mai multor zile:</dt><dd>100 EUR pe zi</dd><dd>Prețul afișat este cel final, facturat pentru client</dd></dl>'],
['<dl><dt>English to Romanian translation:</dt><dd>15 RON per page*<sup><small>*</small></sup></dd><dt>Romanian to English translation:</dt><dd>11 RON per page*<sup><small>*</small></sup></dd><dd><sup><small>*</small></sup>A standard A4 page comprises 2,000 characters with spaces. The price listed is the final price invoiced to the client. </dd></dl>', '<dl><dt>Consecutive interpreting services (Notarial Offices, Police Stations, Courts, etc. ):</dt><dd>100 RON per hour<sup><small>*</small></sup></dd><dt>Simultaneous interpreting services (conferences, radio TV):</dt><dd>100 RON per hour<sup><small>*</small></sup></dd><dd><sup><small>*</small></sup>The first hour is invoiced in full, even when the event lasts for less than one hour. The following hours are invoiced in fractions, every 30 minutes. The price listed is the final price invoiced to the client. </dd></dl>', '<dl><dt>Interpreting services for events covering a full day/ several days:</dt><dd>100 EUR per day</dd><dd>The price listed is the final price invoiced to the client. </dd></dl>']
]
}

var footerSect = {
p7:['Conținutul acestui site are, în primul rând, un scop informativ. Imaginile care ilustrează textele pot fi folosite liber, inclusiv în scopuri comerciale, conform <strong title="pixabay.com">sursei de proveniență</strong>.', 'The content of this site is primarily informative. The pictures illustrating the texts may be used freely, including for commercial purposes, according to their <strong title="pixabay.com">original source</strong>.'],

extlink1:['Imagini gratuite', 'Free pictures'],
extlink2:['Contactează designer-ul', 'Contact the web designer'],
extlink3:['Contactează-mă pentru o traducere / interpretare', 'Contact me for translation/ interpreting services']
}

var aboutContainer = {
	menuBEdu:[['Educație', 'Angajatori', 'Preferințe'], ['Education', 'Employers', 'Hobbies']],
	h2loc:['Locația din prezent: București, România, Uniunea Europeană', 'Current location: Bucharest, Romania, European Union'],
	h3Edu:['Educație','Education'],
	captionEdu:['În Sydney, cu Sydney Haboour Bridge în fundal, 2009 ','In Sydney, with the Sydney Harbour Bridge in the background, 2009'],
	d1LisEdu:['<dt><strong>Diplomă de Master în Dezvoltare și Relații Internaționale (Global Refugee Studies) obținută în urma unui program de studii la Universitatea Aalborg, Danemarca (program în limba engleză)</strong></dt><dd>Perioada: august 2010 - august 2012.</dd><dd>Ca parte a programului de Master, între lunile iulie și decembrie 2011 am participat la un intership în cadrul Fundației ARCA România – un ONG dedicat integrării imigranților și refugiaților aflați în România. Am predat cursuri de limba română străinilor refugiați care se pregăteau pentru examenul de obținere a cetățeniei. Cursanții erau în general vorbitori de engleză sau franceză, astfel că lecțiile au fost predate în aceste limbi. .</dd><dt><strong>Master în Jurnalism Internațional la Dublin City University, Irlanda. În intervalul februarie - iunie 2009 am urmat semestrul de studii la University of Technology, Sydney, Australia, în cadrul unui schimb de experiență.</strong></dt><dd>Perioada: septembrie 2008 - martie 2010.</dd><dt><strong>Licență în Jurnalism, obținută la Universitatea de Vest, Timișoara, 2004</strong></dt><dd>Durata studiilor: 8 semestre.</dd>', '<dt><strong>Master of Science (Msc) in Development and International Relations (Global Refugees Studies), Aalborg University Denmark (Copenhagen campus)</strong></dt><dd>Duration: August 2010 - August 2012.</dd><dd>Between July and December 2011, I completed an internship at ARCA - Romanian Forum for Refugees and Migrants- which is an NGO in Bucharest, specialized in assisting refugees and asylum seekers in their efforts to integrate in Romania. My main responsibility was to teach Romanian language to refugees and asylum seekers. My students were generally English or French speakers and the courses were conducted in either English or French.</dd><dt><strong>Master of Arts (M.A.) in International Journalism, Dublin City University, Ireland</strong></dt><dd>Duration: September 2008 - March 2010.</dd><dd>Between February and June 2009, I was on a study abroad semester at the University of Technology, Sydney, Australia.</dd><dt><strong>Bachelor’s degree in Journalism awarded by the West University Timisoara, Romania, 2004</strong></dt><dd>Duration: 8 semesters.</dd>'],
	sumEdu:['Vezi mai mult...', 'Expand to see more...'],
	d2ListEdu:['<dt><strong>Alte calificări și atestate</strong></dt><dd>Septembrie 2016– Certificat IELTS (International English Language Testing System), obținut la British Council, București. Scor general 8.0 în Modulul Academic.</dd><dd>Iunie 2014 - Autorizație de traducător/ interpret acordată de Ministerul Justiției din România (română - engleză, engleză - română, domeniul juridic).</dd><dd>Decembrie 2013 - Certificat TEFL (Teaching English as a Foreign Language), eliberat de Universitatea Brighton, Marea Britanie</dd><dd>Aprilie 2008 – Certificat TEF (Test d’evaluation en Francais), acordat de Institutul Francez din București. (Citire și ascultare - nivel 5, Vorbire - nivel 4, Scriere - nivel 3).</dd><dd>În iunie 2008 am fost nominalizată pentru trofeul &quot;Tânărul Jurnalist al Anului&quot; la categoria &quot;Politică Internațională și Afaceri Europene&quot;. </dd><dt><strong>Limbi cunoscute:</strong></dt><dd>Engleză – fluent</dd><dd>Franceză – foarte bine</dd><dd>Română – limba maternă</dd>', '<dt><strong>Other qualifications and awards</strong></dt><dd>September 2016 – IELTS Certificate (International English Language Testing System) – awarded by British Council Bucharest. Overall band: 8.0 in the Academic Module.</dd><dd>June 2014 - Authorization for certified translators awarded by the Romanian Ministry of Culture and the Romanian Ministry of Justice (English to Romanian and Romanian to English).</dd><dd>Dec 2013 - TEFL Certificate (Teaching English as a Foreign Language) awarded by the TELF University, Brighton, United Kingdom. I passed the exam with grade A.</dd><dd>April 2008 – TEF Certificate (Test d’evaluation en Francais), awarded by The French Institute, Bucharest (Reading and Listening – level 5, Speaking – level 4, Writing - level 3).</dd><dd>In June 2008 I was nominated for the &quot;Romanian Young Journalist of the Year&quot; Award at the &quot;International Politics and European Affairs&quot; category. </dd><dt><strong>Languages:</strong></dt><dd>English – fluent</dd><dd>French – very good</dd><dd>Romanian – my native language</dd>'],
	h3Empl:['Angajatori', 'Employers'],
	captionEmpl:['Primul Summit UE la care am participat în Bruxelles, 2007', 'My first EU Summit in Brussels, 2007'],
	d1ListEmpl:['<dt><strong>Inova Translations SRL</strong>, București, România</dt><dd>Traducător - interpret de limba engleză</dd><dt><strong title="www.paginadepolitica.ro">Pagina de politica</strong></dt><dd>Editor știri externe</dd><dt><strong>Foreign Policy România</strong></dt><dd>Editor - traducător</dd><dt><strong>Money TV</strong>, București, România</dt><dd>Redactor știri externe</dd><dt><strong>România TV</strong>, București, România</dt><dd>Redactor știri externe</dd><dt><strong>Realitatea TV</strong>, București, România</dt><dd>Redactor știri externe</dd><dt><strong>Antena 1</strong> și <strong>Antena 3</strong>, București România</dt><dd>Redactor știri externe</dd>', '<dt><strong>Inova Translations SRL</strong>, Bucharest, Romania</dt><dd>Position: Translator – interpreter</dd><dt><strong>Pagina de politica</strong></dt><dd>Position: Foreign Affairs Editor</dd><dt><strong>Foreign Policy Romania</strong></dt><dd>Position: Foreign Affairs Editor and translator</dd><dt><strong>Money TV</strong>, Bucharest, Romania</dt><dd>Position: International News Editor</dd><dt><strong>Romania TV</strong>, Bucharest, Romania</dt><dd>Position: International News Editor </dd><dt><strong>Realitatea TV</strong>, Bucharest, Romania</dt><dd>Position: International News Editor </dd><dt><strong>Antena 1</strong> and <strong>Antena 3</strong> TV stations, Bucharest, Romania</dt><dd>Position: International News Editor </dd>'],
	sumEmpl:['Lista nu este completă. Este posibil ca unele companii media menționate să nu mai existe în prezent. Vezi mai mult...', 'The list is not exhaustive. Some of the media companies might no longer exist today. Expand to see more...'],
	d2ListEmpl:['<dt>Corespondent din <strong>Sydney</strong> pentru <strong>Antena 1</strong> și <strong>Antena 3</strong>, în perioada programului de studii în străinătate (2009)</dt><dd>Video-jurnalist (muncă implicând documentarea subiectelor, filmarea, redactarea și montajul, upload-ul materialului pe serverul ftp) </dd><dd>Între martie și iulie 2009 am lucrat, de asemenea, ca reporter pentru <strong>SBS</strong>, postul național de radio australian, în cadrul programului în limba română. M-am ocupat de evenimente relevante pentru comunitatea românească din Sydney. </dd><dt>Corespondent din <strong>Dublin</strong> pentru <strong>Antena 1</strong> și <strong>Antena 3</strong>, în timpul primului program de studii în străinătate (2008 - 2009)</dt><dd>Video-jurnalist</dd><dt>Ziarul <strong>&quot;Cotidianul&quot;</strong>, București, România</dt><dd>Reporter pe domeniul &quot;Afaceri Internaționale&quot;</dd><dt><strong>B1 TV</strong>, București, România</dt><dd>Editor și producător știri externe</dd>', '<dt><strong>Sydney correspondent</strong> for <strong>Antena 1</strong> and <strong>Antena 3</strong> TV stations, during my studies abroad (2009)</dt><dd>Position: Video Journalist </dd><dd>Between March and July 2009, I also acted as a reporter for the <strong>National Australian Radio</strong>, SBS, reporting for the Romanian language programme. Here I covered events that involved the Romanian community in Sydney. </dd><dt><strong>Dublin correspondent</strong> for <strong>Antena 1</strong> and <strong>Antena 3</strong> TV stations, during my studies abroad (2008 - 2009)</dt><dd>Position: Video Journalist </dd><dt><strong>&quot;Cotidianul&quot;</strong> newspaper, Bucharest, Romania</dt><dd>Position: Foreign Affairs Reporter</dd><dt><strong>B1 TV </strong>, Bucharest, Romania</dt><dd>Position: International News Editor and Producer</dd>'],
	h3Hobb:['Preferințe și pasiuni', 'Hobbies'],
	captionHobb:['Înfruntând gerul din Varșovia, Decembrie 2015', 'Freezing in Warsaw, December 2015'],
	liTrav:['Călătoriile', 'Travels'],
	liBooks:['<strong>Cărțile pe teme de politici globale, cărțile SF, filmele SF.</strong> Vezi trailer-ul SF-ului aflat pe primul loc în lista mea de preferințe, <a href="http://www.imdb.com/title/tt1371111/" target="_blank"><strong>Atalsul Norilor.</strong></a><iframe id="movie" class="frame" src="https://www.youtube.com/embed/hWnAqFyaQ5s" allowfullscreen></iframe>', '<strong>Global Politics and SF books, SF movies.</strong> Sneak peak at my favourite SF movie, <a href="http://www.imdb.com/title/tt1371111/" target="_blank"><strong>Cloud Atlas.</strong></a><iframe id="movie" class="frame" src="https://www.youtube.com/embed/hWnAqFyaQ5s" allowfullscreen></iframe>'],
	liMus:['<strong>Muzica bună </strong> (Ascultă câteva dintre piesele mele favorite. Poți trece la piesa următoare cu ajutorul butonului &quot;Next&quot;...)<iframe id="music" class="frame" src="https://www.youtube.com/embed/yE6DNu_avyg" allowfullscreen></iframe>', '<strong>Good music</strong> (try some of my favorites with &quot;Next&quot; button...)<iframe id="music" class="frame" src="https://www.youtube.com/embed/yE6DNu_avyg" allowfullscreen></iframe>'],
	pFoot:['Conținutul acestei pagini este unul informativ. Imaginile provin din arhiva personală a proprietaturlui site-ului, cu excepția imaginii de fundal pentru elementul heading de nivel 1, a compoziției grafice cu steaguri și a videoclipurilor afișate în elementul <i>iframe</i>.', 'The content of this page is primarily informative. All the images belong to the owner&apos; personal archive, except for the level 1 heading&apos; background, the flags map and the videos displayed in the iframe element.'],
	liDesFoot:['Contactează designerul web', 'Contact the web designer'],
	liTradFoot:['Contactează-mă pentru o traducere / interpretare', 'Contact me for translation/ interpreting services']
}

//window.$itPriceContent = itPriceContent;
window.$TechContainer = TechContainer;
window.$LawContainer = LawContainer;
window.$LiterContainer = LiterContainer;
window.$EconContainer = EconContainer;
window.$LoremIpsum = LoremIpsum;
window.$aboutContainer = aboutContainer;

window.$navSect = navSect;
window.$mainSect = mainSect;
window.$footerSect = footerSect;

})();

